# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stadsbudsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='posted',
        ),
        migrations.AddField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
